### PR TITLE
Fixed 401 error for create call in Gem

### PR DESCRIPTION
**Pull request by sumitsourav**
Screenshot of the 401 error not coming in the errors before the change:-
Screenshot 2022-12-08 at 5 33 10 PM

Screenshot of the 401 error coming in the errors attribute after the change:-
Screenshot 2022-12-08 at 5 30 04 PM

Screenshot for the successful Webhook create call:-
Screenshot 2022-12-08 at 6 50 15 PM

Screenshot for 400 error when creating a Webhook:-
Screenshot 2022-12-08 at 6 55 54 PM

Screenshot of 401 error for the feature flag post call:-
Screenshot 2022-12-08 at 7 00 53 PM

### CODE REVIEW

**Comment by rishirajkumar97** [comment]
@sumitsourav  can you add screenshots for other endpoints create or get or update as well?
we might need to ensure this 401 handling works for other codes as well as the code change is generic something like a 500, 404 ? can you add them as well in screenshots

**Comment by sumitsourav** [comment]
> @sumitsourav can you add screenshots for other endpoints create or get or update as well? we might need to ensure this 401 handling works for other codes as well as the code change is generic something like a 500, 404 ? can you add them as well in screenshots

The changes are in the post_result method which are called only for the create method not for update or get method.

But i will add the screenshots of create for other models as well.

**Comment by rishirajkumar97** [comment]
@sumitsourav  can we bump the version of the gem as well then only we would be able to use this change

**Comment by sumitsourav** [comment]
> @sumitsourav can we bump the version of the gem as well then only we would be able to use this change

Updated the gem version @rishirajkumar97

**Pull request merged**
